### ISSUE TITLE
[DeleteEmbeds] Enable deleting attachments

### ISSUE THREAD

**Issue by Delphox** [c10udburst-discord/aliucord-plugins#12]
Desktop/Web Discord allows deleting attachments with the little X on attachments as well, as long as there's more than one upload in same message, or text, but it shouldn't be an issue to blanket enable the Delete Embed option as long as the message has any kind of embed/attachment (yes file uploads are deletable as well, the X shows up).

**Comment by C10udburst** [comment]
sorry that it took so long lol. Delete embeds will now let you remove all attachements if the message was send by you
