### ISSUE TITLE
[TextReplace]{BUG} Only works after menu is opened

### ISSUE THREAD

**Issue by MeFinity** [c10udburst-discord/aliucord-plugins#9]
I've been seeing that the TextReplace plugin doesn't work some of the times and today I've finally found why
it only replaces text after the plugin setting is opened
![bugreport](https://user-images.githubusercontent.com/72972952/141955448-db542d35-290f-4975-92a8-d6103f986bbe.jpg)
i did not edit this image,it actually won't replace texts that has been sent before the setting is opened,it only replaces text that gets sent after the setting is opened

Removed the annoying YT Embed with RemoveEmbed

**Comment by C10udburst** [comment]
yeah, that's how it works. it modifies message when they are received. You can restart discord and both urls should be changed.

**Comment by C10udburst** [comment]
sorry, I didn't read your issue properly, anyway fixed in d09d61c7d3fd62b77ebdf44db5314a3569126d3f
